//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2019Solver_Silver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2019Solver_Silver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99711
        ///136867
        ///97107
        ///108257
        ///57509
        ///129721
        ///139889
        ///91988
        ///54465
        ///129229
        ///59122
        ///97391
        ///57509
        ///70687
        ///72733
        ///137687
        ///123889
        ///53484
        ///71869
        ///144816
        ///83856
        ///131570
        ///68905
        ///66648
        ///124392
        ///59964
        ///80553
        ///93881
        ///56253
        ///76282
        ///127377
        ///110425
        ///59914
        ///76294
        ///81888
        ///88986
        ///132544
        ///70423
        ///124018
        ///122121
        ///53231
        ///148042
        ///108810
        ///75092
        ///60185
        ///94065
        ///130221
        ///121319
        ///87502
        ///90029
        ///86186
        ///113956
        ///143744
        ///133441
        ///142914
        ///112218
        ///66629
        ///144965
        ///135476
        ///111537
        ///51709
        ///125198
        ///72098
        ///79625
        ///105068
        ///119597
        ///71611
        ///122186
        ///95752 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent1 {
            get {
                return ResourceManager.GetString("Advent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0,0,3,1,1,2,3,1,3,4,3,1,5,0,3,2,1,13,19,1,10,19,23,2,9,23,27,1,6,27,31,1,10,31,35,1,35,10,39,1,9,39,43,1,6,43,47,1,10,47,51,1,6,51,55,2,13,55,59,1,6,59,63,1,10,63,67,2,67,9,71,1,71,5,75,1,13,75,79,2,79,13,83,1,83,9,87,2,10,87,91,2,91,6,95,2,13,95,99,1,10,99,103,2,9,103,107,1,107,5,111,2,9,111,115,1,5,115,119,1,9,119,123,2,123,6,127,1,5,127,131,1,10,131,135,1,135,6,139,1,139,5,143,1,143,9,147,1,5,147,151,1,151,13,155,1,5,155,159,1,2,159,163,1,163,6,0,99,2,0,14,0.
        /// </summary>
        internal static string Advent2 {
            get {
                return ResourceManager.GetString("Advent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R994,D213,L483,U102,L292,U153,L123,D568,R54,U482,L971,D679,L17,U492,R448,U75,R472,D209,R872,D271,L271,U175,L373,D968,R867,U191,R746,U717,L918,D171,L205,D399,R889,D626,R683,D853,R571,U42,L406,D390,R716,U364,L596,U226,L34,D805,R474,D304,R54,D854,L140,U923,L800,D833,L127,D576,R779,U433,L270,U602,L266,D874,R275,D146,L469,U623,R932,D564,R683,D769,L824,U818,L743,U846,R607,D860,R989,U927,R467,D465,R915,D531,L206,U366,R476,U516,R688,D144,L3,D612,L50,D519,R765,D684,L100,U233,R898,U957,R335,D614,R672,U428,R104,U294,L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent3 {
            get {
                return ResourceManager.GetString("Advent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 165432-707912.
        /// </summary>
        internal static string Advent4 {
            get {
                return ResourceManager.GetString("Advent4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,225,1,225,6,6,1100,1,238,225,104,0,1001,210,88,224,101,-143,224,224,4,224,1002,223,8,223,101,3,224,224,1,223,224,223,101,42,92,224,101,-78,224,224,4,224,1002,223,8,223,1001,224,3,224,1,223,224,223,1101,73,10,225,1102,38,21,225,1102,62,32,225,1,218,61,224,1001,224,-132,224,4,224,102,8,223,223,1001,224,5,224,1,224,223,223,1102,19,36,225,102,79,65,224,101,-4898,224,224,4,224,102,8,223,223,101,4,224,224,1,224,223,223,1101,66,56,224,1001,224,-122,224,4,224,102,8,223,223,1001,224,2,224,1,224,223,223,1002,58,82, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent5 {
            get {
                return ResourceManager.GetString("Advent5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YQ2)CYG
        ///63M)X4N
        ///7YF)LRN
        ///K2B)PVC
        ///394)195
        ///W68)QNR
        ///XDS)SX7
        ///JWG)789
        ///6RR)4R1
        ///S9Y)M1X
        ///VDC)R4V
        ///7G4)4YZ
        ///XK2)K4M
        ///R7M)ZHC
        ///Q14)ZS1
        ///GJF)4RM
        ///YQ2)K4G
        ///T98)2GB
        ///YRP)3Q9
        ///SD7)XRN
        ///DYR)GQZ
        ///4NV)T6C
        ///8LL)WLB
        ///9GX)T7C
        ///673)Q4F
        ///V2F)B5Q
        ///BZN)RPX
        ///Y2T)X6B
        ///P89)F2S
        ///WFQ)JNL
        ///JJ7)QK7
        ///HYQ)RWS
        ///Q97)V15
        ///NHX)XND
        ///MHP)P5L
        ///PPL)H6G
        ///KVV)535
        ///8NK)9FG
        ///B6X)6MG
        ///MX2)T8M
        ///7NC)V6V
        ///ZP1)SN7
        ///FY5)PJX
        ///J9S)H1F
        ///LRZ)VPY
        ///PSG)S74
        ///DGK)N44
        ///QJ1)BRR
        ///2XM)LVG
        ///ZG1)QNQ
        ///72L)QJ1
        ///GNQ)XT4
        ///1XJ)PKH
        ///T3M)ZB7
        ///JQS)B53
        ///CNV)7PL
        ///4MF)9YJ        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent6 {
            get {
                return ResourceManager.GetString("Advent6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,8,1001,8,10,8,105,1,0,0,21,34,47,72,81,102,183,264,345,426,99999,3,9,102,5,9,9,1001,9,3,9,4,9,99,3,9,101,4,9,9,1002,9,3,9,4,9,99,3,9,102,3,9,9,101,2,9,9,102,5,9,9,1001,9,3,9,1002,9,4,9,4,9,99,3,9,101,5,9,9,4,9,99,3,9,101,3,9,9,1002,9,5,9,101,4,9,9,102,2,9,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,101,2,9,9,4,9,3,9,102,2,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,1002,9,2,9,4,9,3,9,1001,9,1,9,4,9,3,9,1001,9,1,9,4,9,3,9,1001,9,2,9,4,9,3,9,101,1,9,9,4,9,99,3,9,101,1,9,9,4,9,3,9,1001,9,2,9,4,9,3,9,102,2,9,9,4,9, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent7 {
            get {
                return ResourceManager.GetString("Advent7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01234
        ///10234
        ///20134
        ///02134
        ///12034
        ///21034
        ///21304
        ///12304
        ///32104
        ///23104
        ///13204
        ///31204
        ///30214
        ///03214
        ///23014
        ///32014
        ///02314
        ///20314
        ///10324
        ///01324
        ///31024
        ///13024
        ///03124
        ///30124
        ///40123
        ///04123
        ///14023
        ///41023
        ///01423
        ///10423
        ///10243
        ///01243
        ///21043
        ///12043
        ///02143
        ///20143
        ///24103
        ///42103
        ///12403
        ///21403
        ///41203
        ///14203
        ///04213
        ///40213
        ///20413
        ///02413
        ///42013
        ///24013
        ///34012
        ///43012
        ///03412
        ///30412
        ///40312
        ///04312
        ///04132
        ///40132
        ///10432
        ///01432
        ///41032
        ///14032
        ///13042
        ///31042
        ///01342
        ///10342
        ///30142
        ///03142
        ///43102
        ///34102
        ///14302
        ///41302
        ///31402
        ///13402
        ///23401
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent7Helper {
            get {
                return ResourceManager.GetString("Advent7Helper", resourceCulture);
            }
        }
    }
}
