//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent8_12Solver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent8_12Solver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###..#########.#####.
        ///.####.#####..####.#.#
        ///.###.#.#.#####.##..##
        ///##.####.#.###########
        ///###...#.####.#.#.####
        ///#.##..###.########...
        ///#.#######.##.#######.
        ///.#..#.#..###...####.#
        ///#######.##.##.###..##
        ///#.#......#....#.#.#..
        ///######.###.#.#.##...#
        ///####.#...#.#######.#.
        ///.######.#####.#######
        ///##.##.##.#####.##.#.#
        ///###.#######..##.#....
        ///###.##.##..##.#####.#
        ///##.########.#.#.#####
        ///.##....##..###.#...#.
        ///#..#.####.######..###
        ///..#.####.############
        ///..##...###..#########.
        /// </summary>
        internal static string Advent10 {
            get {
                return ResourceManager.GetString("Advent10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......#.#.
        ///#..#.#....
        ///..#######.
        ///.#.#.###..
        ///.#..#.....
        ///..#....#.#
        ///#..#....#.
        ///.##.#..###
        ///##...#..#.
        ///.#....####.
        /// </summary>
        internal static string Advent10Test1 {
            get {
                return ResourceManager.GetString("Advent10Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..#..###
        ///####.###.#
        ///....###.#.
        ///..###.##.#
        ///##.##.#.#.
        ///....###..#
        ///..#.#..#.#
        ///#..#.#.###
        ///.##...##.#
        ///.....#.#...
        /// </summary>
        internal static string Advent10Test2 {
            get {
                return ResourceManager.GetString("Advent10Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..##.###...#######
        ///##.############..##.
        ///.#.######.########.#
        ///.###.#######.####.#.
        ///#####.##.#.##.###.##
        ///..#####..#.#########
        ///####################
        ///#.####....###.#.#.##
        ///##.#################
        ///#####.##.###..####..
        ///..######..##.#######
        ///####.##.####...##..#
        ///.#####..#.######.###
        ///##...#.##########...
        ///#.##########.#######
        ///.####.#.###.###.#.##
        ///....##.##.###..#####
        ///.#.#.###########.###
        ///#.#.#.#####.####.###
        ///###.##.####.##.#..##.
        /// </summary>
        internal static string Advent10Test3 {
            get {
                return ResourceManager.GetString("Advent10Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10222212222222202220222202022222022222222022222222122221220222022222222222222222220222220220222200002222012222122222222222222222222222222222221022222202222222222222212222222212222222222222222222222222122221221222022222222222222202220222221221222201212222012222222222222222222222222222222222222022222201222222222222202222222212022222222222222222222222022221210222122222222222222222221222220220222220212222222222222222222222222222222222222222222222222211222212222222202220222202022222022222222222222222022220212222 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent8 {
            get {
                return ResourceManager.GetString("Advent8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1102,34463338,34463338,63,1007,63,34463338,63,1005,63,53,1102,1,3,1000,109,988,209,12,9,1000,209,6,209,3,203,0,1008,1000,1,63,1005,63,65,1008,1000,2,63,1005,63,904,1008,1000,0,63,1005,63,58,4,25,104,0,99,4,0,104,0,99,4,17,104,0,99,0,0,1102,26,1,1005,1101,0,24,1019,1102,1,32,1007,1101,0,704,1027,1102,0,1,1020,1101,0,348,1029,1102,28,1,1002,1101,34,0,1016,1102,29,1,1008,1102,1,30,1013,1102,25,1,1012,1101,0,33,1009,1102,1,37,1001,1101,31,0,1017,1101,245,0,1022,1102,39,1,1000,1101,27,0,1011,1102,770,1,1025,1101 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent9 {
            get {
                return ResourceManager.GetString("Advent9", resourceCulture);
            }
        }
    }
}
