//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent8_12Solver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent8_12Solver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###..#########.#####.
        ///.####.#####..####.#.#
        ///.###.#.#.#####.##..##
        ///##.####.#.###########
        ///###...#.####.#.#.####
        ///#.##..###.########...
        ///#.#######.##.#######.
        ///.#..#.#..###...####.#
        ///#######.##.##.###..##
        ///#.#......#....#.#.#..
        ///######.###.#.#.##...#
        ///####.#...#.#######.#.
        ///.######.#####.#######
        ///##.##.##.#####.##.#.#
        ///###.#######..##.#....
        ///###.##.##..##.#####.#
        ///##.########.#.#.#####
        ///.##....##..###.#...#.
        ///#..#.####.######..###
        ///..#.####.############
        ///..##...###..#########.
        /// </summary>
        internal static string Advent10 {
            get {
                return ResourceManager.GetString("Advent10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......#.#.
        ///#..#.#....
        ///..#######.
        ///.#.#.###..
        ///.#..#.....
        ///..#....#.#
        ///#..#....#.
        ///.##.#..###
        ///##...#..#.
        ///.#....####.
        /// </summary>
        internal static string Advent10Test1 {
            get {
                return ResourceManager.GetString("Advent10Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..#..###
        ///####.###.#
        ///....###.#.
        ///..###.##.#
        ///##.##.#.#.
        ///....###..#
        ///..#.#..#.#
        ///#..#.#.###
        ///.##...##.#
        ///.....#.#...
        /// </summary>
        internal static string Advent10Test2 {
            get {
                return ResourceManager.GetString("Advent10Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..##.###...#######
        ///##.############..##.
        ///.#.######.########.#
        ///.###.#######.####.#.
        ///#####.##.#.##.###.##
        ///..#####..#.#########
        ///####################
        ///#.####....###.#.#.##
        ///##.#################
        ///#####.##.###..####..
        ///..######..##.#######
        ///####.##.####...##..#
        ///.#####..#.######.###
        ///##...#.##########...
        ///#.##########.#######
        ///.####.#.###.###.#.##
        ///....##.##.###..#####
        ///.#.#.###########.###
        ///#.#.#.#####.####.###
        ///###.##.####.##.#..##.
        /// </summary>
        internal static string Advent10Test3 {
            get {
                return ResourceManager.GetString("Advent10Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ####
        ///####
        ///####
        ///####.
        /// </summary>
        internal static string Advent10Test4 {
            get {
                return ResourceManager.GetString("Advent10Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#....#####...#..
        ///##...##.#####..##
        ///##...#...#.#####.
        ///..#.....#...###..
        ///..#.#.....#....##.
        /// </summary>
        internal static string Advent10Test5 {
            get {
                return ResourceManager.GetString("Advent10Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,8,1005,8,304,1106,0,11,0,0,0,104,1,104,0,3,8,102,-1,8,10,101,1,10,10,4,10,1008,8,1,10,4,10,1002,8,1,29,2,103,1,10,1,106,18,10,3,8,102,-1,8,10,1001,10,1,10,4,10,1008,8,1,10,4,10,102,1,8,59,2,102,3,10,2,1101,12,10,3,8,102,-1,8,10,1001,10,1,10,4,10,108,0,8,10,4,10,101,0,8,88,3,8,102,-1,8,10,1001,10,1,10,4,10,108,1,8,10,4,10,101,0,8,110,2,108,9,10,1006,0,56,3,8,102,-1,8,10,1001,10,1,10,4,10,108,0,8,10,4,10,101,0,8,139,1,108,20,10,3,8,102,-1,8,10,101,1,10,10,4,10,108,0,8,10,4,10,102,1,8,165,1,104,9,10,3,8,102, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent11 {
            get {
                return ResourceManager.GetString("Advent11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Advent11Test {
            get {
                return ResourceManager.GetString("Advent11Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;x=7, y=10, z=17&gt;
        ///&lt;x=-2, y=7, z=0&gt;
        ///&lt;x=12, y=5, z=12&gt;
        ///&lt;x=5, y=-8, z=6&gt;.
        /// </summary>
        internal static string Advent12 {
            get {
                return ResourceManager.GetString("Advent12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,380,379,385,1008,2267,709926,381,1005,381,12,99,109,2268,1101,0,0,383,1101,0,0,382,20101,0,382,1,21002,383,1,2,21102,37,1,0,1105,1,578,4,382,4,383,204,1,1001,382,1,382,1007,382,37,381,1005,381,22,1001,383,1,383,1007,383,22,381,1005,381,18,1006,385,69,99,104,-1,104,0,4,386,3,384,1007,384,0,381,1005,381,94,107,0,384,381,1005,381,108,1105,1,161,107,1,392,381,1006,381,161,1101,-1,0,384,1106,0,119,1007,392,35,381,1006,381,161,1101,0,1,384,21002,392,1,1,21102,1,20,2,21102,1,0,3,21101,138,0,0,1106,0,549,1,392,38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent13 {
            get {
                return ResourceManager.GetString("Advent13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10222212222222202220222202022222022222222022222222122221220222022222222222222222220222220220222200002222012222122222222222222222222222222222221022222202222222222222212222222212222222222222222222222222122221221222022222222222222202220222221221222201212222012222222222222222222222222222222222222022222201222222222222202222222212022222222222222222222222022221210222122222222222222222221222220220222220212222222222222222222222222222222222222222222222222211222212222222202220222202022222022222222222222222022220212222 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent8 {
            get {
                return ResourceManager.GetString("Advent8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1102,34463338,34463338,63,1007,63,34463338,63,1005,63,53,1102,1,3,1000,109,988,209,12,9,1000,209,6,209,3,203,0,1008,1000,1,63,1005,63,65,1008,1000,2,63,1005,63,904,1008,1000,0,63,1005,63,58,4,25,104,0,99,4,0,104,0,99,4,17,104,0,99,0,0,1102,26,1,1005,1101,0,24,1019,1102,1,32,1007,1101,0,704,1027,1102,0,1,1020,1101,0,348,1029,1102,28,1,1002,1101,34,0,1016,1102,29,1,1008,1102,1,30,1013,1102,25,1,1012,1101,0,33,1009,1102,1,37,1001,1101,31,0,1017,1101,245,0,1022,1102,39,1,1000,1101,27,0,1011,1102,770,1,1025,1101 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Advent9 {
            get {
                return ResourceManager.GetString("Advent9", resourceCulture);
            }
        }
    }
}
